// Actions
const ADD_USER = "ADD_USER";
const EDIT_USER = "EDIT_USER";
const SUBMIT_EDIT = "SUBMIT_EDIT";
const REMOVE_USER = "REMOVE_USER";
const TOGGLE_EDIT = "TOGGLE_EDIT";
const RESET_FORM = "RESET_FORM";

module.exports = {
  ADD_USER,
  EDIT_USER,
  SUBMIT_EDIT,
  REMOVE_USER,
  TOGGLE_EDIT,
  RESET_FORM
};